### ISSUE TITLE
Cutscene making [WIP]

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [ct-js/ct-js-old#58]
In GitLab by @CoMiGo on Feb 25, 2019, 21:41

```js
const video = document.createElement('video');
video.className = 'aFullscreenVideo'; /* надо написать CSS-класс, чтобы заполнить весь экран */
const onPlay = function (e) {
   document.body.appendChild(video);
};
const onComplete = function (e) {
   document.body.removeChild(video);
   /* Видео кончилось. Тут, например, переход в другую комнату */
};
video.addEventListener('canplaythrough', onPlay);
video.addEventListener('ended', onComplete);

video.controls = false;
video.autoplay = true;
video.src = './someVideo.mp4';
video.load();
```

```css
.aFullscreenVideo {
    position: fixed;
    z-index: 100;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: black;
}
```
